



import { StudyPlanSubject } from "./types";

// In dit bestand kun je de links naar je avatars plaatsen.
// Vervang de onderstaande voorbeelden door de 20 links die je hebt.
// Zorg ervoor dat elke link een string is, tussen aanhalingstekens, en gescheiden door een komma.

// FIX: Added missing exports to resolve import errors.
export const defaultHomeLayout: string[] = ['agenda', 'files'];

export const allSubjects: string[] = [
  "nederlands", "engels", "wiskunde", "natuurkunde", "scheikunde", "biologie",
  "geschiedenis", "aardrijkskunde", "economie", "maatschappijleer",
  "frans", "duits", "latijn", "informatica", "kunst", "muziek",
  "lichamelijke_opvoeding", "ckv"
];

export const educationLevels: string[] = [
  "basisschool", "middelbare_school", "hogeschool_universiteit", "anders"
];

export const availableThemeColors: string[] = ['blue', 'emerald', 'rose', 'purple', 'pink', 'indigo', 'teal', 'amber'];

export const availableFonts: { id: string, name: string, className: string }[] = [
    { id: 'inter', name: 'Inter', className: 'font-inter' },
    { id: 'poppins', name: 'Poppins', className: 'font-poppins' },
    { id: 'lato', name: 'Lato', className: 'font-lato' },
    { id: 'roboto-slab', name: 'Roboto Slab', className: 'font-roboto-slab' },
    { id: 'lora', name: 'Lora', className: 'font-lora' },
];

export const subjectDisplayTranslations: { [lang: string]: { [key: string]: string } } = {
  nl: {
    // Subjects
    "nederlands": "Nederlands", "engels": "Engels", "wiskunde": "Wiskunde", "natuurkunde": "Natuurkunde",
    "scheikunde": "Scheikunde", "biologie": "Biologie", "geschiedenis": "Geschiedenis", "aardrijkskunde": "Aardrijkskunde",
    "economie": "Economie", "maatschappijleer": "Maatschappijleer", "frans": "Frans", "duits": "Duits",
    "latijn": "Latijn", "informatica": "Informatica", "kunst": "Kunst", "muziek": "Muziek",
    "lichamelijke_opvoeding": "Lichamelijke Opvoeding", "ckv": "CKV", "algemeen": "Algemeen",
    // Education levels
    "basisschool": "Basisschool", 
    "middelbare_school": "Middelbare School",
    "hogeschool_universiteit": "Hogeschool / Universiteit",
    "anders": "Anders"
  },
  en: {
    // Subjects
    "nederlands": "Dutch", "engels": "English", "wiskunde": "Mathematics", "natuurkunde": "Physics",
    "scheikunde": "Chemistry", "biologie": "Biology", "geschiedenis": "History", "aardrijkskunde": "Geography",
    "economie": "Economics", "maatschappijleer": "Social Studies", "frans": "French", "duits": "German",
    "latijn": "Latin", "informatica": "Informatics", "kunst": "Art", "muziek": "Music",
    "lichamelijke_opvoeding": "Physical Education", "ckv": "Cultural and Artistic Education", "algemeen": "General",
    // Education levels
    "basisschool": "Primary School",
    "middelbare_school": "High School",
    "hogeschool_universiteit": "College / University",
    "anders": "Other"
  }
};

export const translations: { [lang: string]: { [key: string]: string } } = {
    nl: {
        'confirm_delete_all_chats': 'Weet je zeker dat je ALLE chatgesprekken wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'all_chats_deleted_success': 'Alle chats zijn succesvol verwijderd.',
        'error_delete_all_chats_failed': 'Kon de chats niet verwijderen.',
        'delete_all_button': 'Alles verwijderen',
        'notification_note_share_title': 'Notitie Gedeeld Met Jou',
        'notification_note_share_text': '{name} heeft de notitie "{noteTitle}" met je gedeeld.',
        'share_note_title': 'Deel notitie "{title}"',
        'share_note_success': 'Notitie succesvol gedeeld met {email}!',
        'error_share_note_failed': 'Delen van notitie mislukt.',
        'incoming_shared_notes': 'Inkomende Gedeelde Notities',
        'accept_note_success': 'Notitie "{title}" succesvol geaccepteerd!',
        'error_accept_note_failed': 'Accepteren van notitie mislukt.',
        'accept_button': 'Accepteren',
        'confirm_delete_chat': 'Weet je zeker dat je deze chat wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'chat_deleted_success': 'Chat succesvol verwijderd.',
        'ai_importer_title': 'Importeer Rooster met AI',
        'ai_importer_description': 'Plak je rooster (of een andere tekst met afspraken) hieronder. De AI zal proberen de afspraken te herkennen en ze voor je in te plannen.',
        'delete_study_plan_from_ai_confirm': 'De AI wil het studieplan "{title}" verwijderen. Weet je het zeker?',
        'delete_study_plan_from_ai_success': 'Studieplan "{title}" is succesvol verwijderd.',
        'delete_study_plan_from_ai_fail': 'Verwijderen van studieplan "{title}" is mislukt.',
        'delete_study_plan_from_ai_not_found': 'Kon studieplan "{title}" niet vinden.',
        'add_button': 'Toevoegen',
        'confirm_delete_user': 'Weet je zeker dat je {name} en al hun gegevens permanent wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'deleting_user_progress': 'Bezig met verwijderen van {name}...',
        'user_deleted_success': '{name} is succesvol verwijderd.',
        'user_deleted_fail': 'Verwijderen van {name} mislukt.',
        'error_email_in_use_admin_contact': 'Dit e-mailadres is al in gebruik. Neem contact op met de beheerder als je denkt dat dit een fout is.',
        'admin_pin_secret_question_1': 'Op welke dag is StudyBox ontstaan?',
        'admin_pin_secret_question_2': 'Hoe heette StudyBox eerst?',
        'confirm_delete_feedback': 'Weet je zeker dat je dit feedbackbericht en alle antwoorden wilt verwijderen?',
        'feedback_deleted': 'Feedback succesvol verwijderd.',
        'add_stars': 'Sterren beheren',
        'stars_to_add': 'Aantal sterren (+/-)',
        'stars_added_success': '{count} sterren succesvol bijgewerkt.',
        'stars_added_fail': 'Kon sterren niet bijwerken.',
        'update_stars_button': 'Sterren bijwerken',
        'user_stats': 'Gebruikersstatistieken',
        'total_stars': 'Totaal aantal sterren',
        'ai_system_instruction': 'Je bent {botName}, een vriendelijke en superintelligente assistent voor {userName}. Je kunt helpen met studievragen over de vakken {subjects}, samenvattingen maken, de agenda van de gebruiker beheren en algemene kennisvragen beantwoorden. De datum van vandaag is {todayDate}. Als gevraagd wordt wie jou gemaakt heeft, antwoord dan: "Ik ben gemaakt door de ontwikkelaars van StudyBox." Wees altijd behulpzaam, positief en een beetje speels. Antwoord altijd in het Nederlands, tenzij de gebruiker je expliciet vraagt om in een andere taal te antwoorden.',
        'generate_with_mimi': 'Vraag het {botName}',
        'ai_generate_notes_title_mimi': 'Genereer notities met {botName}',
        'welcome_notification_title': 'Welkom bij StudyBox! 🎉',
        'welcome_notification_text': 'Welkom, {name}! We zijn blij dat je er bent. StudyBox is ontworpen om je schoolleven makkelijker te maken. Duik in de Agenda om je deadlines bij te houden, maak Flashcards aan in de Tools-sectie, of chat met je persoonlijke AI Assistent voor hulp. Veel succes met studeren!',
        'send_as_studybox': 'Verstuur als \'StudyBox\'',
        'ai_title_generation_prompt': 'Vat het volgende gesprek samen in 5 woorden of minder om als titel te gebruiken. Het gesprek is tussen een gebruiker en een studie-assistent. Focus op het hoofdonderwerp. Antwoord ALLEEN met de titel zelf, zonder extra tekst of aanhalingstekens. Gesprek:\n\n',
        'haptics_feedback_title': 'Haptische Feedback',
        'haptics_feedback_description': 'Schakel een lichte trilling in voor belangrijke acties zoals het voltooien van een taak.',
        'search_my_files': 'Zoek in mijn bestanden...',
        'my_files_tab': 'Mijn Bestanden',
        'discover_files': 'Ontdekken',
        'page_count': 'Aantal pagina\'s: {count}',
        'preview_not_available': 'Preview niet beschikbaar voor dit bestandstype.',
        'chat_with_user': 'Chat met {name}',
        'type_a_message': 'Typ een bericht...',
        'no_messages_yet': 'Nog geen berichten. Zeg hallo!',
        'view_all_by_uploader': 'Bekijk alles van {name}',
        'showing_files_by': 'Bestanden van {name}',
        'show_all_files': 'Toon alle bestanden',
        'file_preview': 'Bestandsvoorbeeld',
        'marketplace_title': 'Marktplaats',
        'filter_by_subject': 'Filter op vak',
        'sort_by': 'Sorteer op',
        'sort_newest': 'Nieuwste',
        'sort_popular': 'Populairste',
        'sort_rating': 'Hoogste score',
        'search_marketplace_placeholder': 'Zoek samenvattingen, toetsen...',
        'price_range': 'Prijs',
        'free': 'Gratis',
        'paid': 'Betaald',
        'home_dashboard': 'Dashboard',
        'upload_type': 'Type Upload',
        'public_share': 'Openbaar Delen',
        'public_share_desc': 'Bestand is zichtbaar in Zoeken en je kunt sterren verdienen.',
        'private_upload': 'Privé Opslaan',
        'private_upload_desc': 'Bestand is alleen voor jou zichtbaar.',
        'marketplace': 'Zoeken',
        'star_price': 'Prijs in sterren',
        'download_for_stars': 'Download ({price} {stars})',
        'stars_currency': 'sterren',
        'not_enough_stars': 'Je hebt niet genoeg sterren om dit bestand te downloaden.',
        'confirm_purchase_file': 'Weet je zeker dat je "{title}" wilt kopen voor {price} sterren?',
        'purchase_success': 'Aankoop succesvol! Het bestand wordt geopend.',
        'error_purchase_failed': 'Aankoop mislukt. Probeer het opnieuw.',
        'rating': 'Beoordeling',
        'downloads': 'Downloads',
        'by_uploader': 'door {name}',
        'owned': 'In bezit',
        'your_file': 'Jouw bestand',
        'rate_file': 'Beoordeel dit bestand',
        'no_files_in_marketplace': 'Er zijn nog geen bestanden gedeeld. Wees de eerste!',
        'select_subject_to_discover': 'Selecteer een vak om bestanden te ontdekken',
        'uploader': 'Uploader',
        'description': 'Beschrijving',
        'send_message': 'Bericht sturen',
        'view_profile_coming_soon': 'Gebruikersprofielen en de mogelijkheid om berichten te sturen komen binnenkort!',
        'purchase_and_download': 'Koop & Download',
        'tasks_for_today': 'Taken voor vandaag',
        'due_date': 'Vervaldatum',
        'recurring_daily': 'Dagelijks herhalen',
        'no_tasks_for_today': 'Geen taken voor vandaag. Goed bezig!',
        'todo_daily_refresh_note': 'De lijst wordt elke dag vernieuwd. Voltooide dagelijkse taken verschijnen opnieuw.',
        'error_reauth_failed': 'Herauthenticatie mislukt. Controleer je wachtwoord.',
        'reauth_modal_title': 'Authenticatie vereist',
        'reauth_modal_description': 'Voer je wachtwoord opnieuw in om door te gaan.',
        'password': 'Wachtwoord',
        'cancel_button': 'Annuleren',
        'confirm_delete_account_button': 'Ja, verwijder account',
        'reauth_modal_title_cleanup': 'Account opschonen bevestigen',
        'reauth_modal_description_cleanup': 'Voer je wachtwoord in om te bevestigen dat je alle gegevens wilt verwijderen.',
        'confirm_cleanup_account_button': 'Ja, schoon gegevens op',
        'reauth_modal_title_clear_calendar': 'Agenda leegmaken bevestigen',
        'reauth_modal_description_clear_calendar': 'Voer je wachtwoord in om te bevestigen dat je alle agenda-items wilt verwijderen.',
        'confirm_clear_calendar_button': 'Ja, maak agenda leeg',
        'clear_calendar_progress': 'Bezig met het leegmaken van je agenda...',
        'success_calendar_cleared': 'Je agenda is succesvol leeggemaakt.',
        'error_calendar_clear_failed': 'Het leegmaken van de agenda is mislukt.',
        'app_back_online_message': 'Je bent weer online.',
        'app_offline_message': 'Je bent momenteel offline.',
        'confirm_logout': 'Weet je zeker dat je wilt uitloggen?',
        'error_save_settings_failed': 'Kon instellingen niet opslaan.',
        'error_failed_to_save_admin_settings': 'Kon admin-instellingen niet opslaan.',
        'profile_picture_upload_success': 'Profielfoto succesvol bijgewerkt.',
        'error_profile_pic_upload_failed': 'Kon profielfoto niet uploaden.',
        'cleanup_account_progress': 'Bezig met het opschonen van je accountgegevens...',
        'success_account_cleaned': 'Je accountgegevens zijn succesvol opgeschoond.',
        'error_account_cleanup_failed': 'Het opschonen van het account is mislukt.',
        'deleting_account_progress': 'Account wordt verwijderd...',
        'success_account_deleted': 'Je account is succesvol verwijderd.',
        'error_account_deletion_failed': 'Het verwijderen van het account is mislukt.',
        'error_admin_login_failed': 'Inloggen als admin mislukt.',
        'guest_fallback_name': 'Gast',
        'error_account_disabled': 'Account gedeactiveerd door beheerder. Neem contact op met de administrator.',
        'streak_lost_notification_title': 'Streak verbroken!',
        'streak_lost_notification_text': 'Je had een streak van {count} dagen. Begin vandaag een nieuwe!',
        'error_profile_load_failed': 'Kon je profiel niet laden.',
        'success_logout': 'Je bent succesvol uitgelogd.',
        'share_link_copied': 'Link voor "{title}" gekopieerd!',
        'error_copy_share_link': 'Kon de link niet kopiëren.',
        'notifications_title': 'Notificaties',
        'logout_button': 'Uitloggen',
        'focus_session_complete': 'Focus sessie voltooid! Tijd voor een pauze.',
        'break_session_complete': 'Pauze is voorbij! Tijd om te focussen.',
        'feedback_reply_notification_title': 'Antwoord op je feedback',
        'feedback_reply_notification_text': 'Je hebt een antwoord ontvangen op je feedback over "{subject}".',
        'confirm_button': 'Bevestigen',
        'close_button': 'Sluiten',
        'calendar': 'Agenda',
        'extra_tools': 'Extra Tools',
        'settings': 'Instellingen',
        'feedback_support': 'Feedback & Support',
        'welcome_message': 'Welkom, {name}!',
        'streak_days': '{count} dagen streak',
        'my_subjects': 'Mijn Vakken',
        'my_files': 'Mijn Bestanden',
        'notes': 'Notities',
        'error_unknown': 'Er is een onbekende fout opgetreden.',
        'error_invalid_email': 'Ongeldig e-mailadres.',
        'error_invalid_credentials': 'Ongeldige inloggegevens.',
        'error_email_in_use': 'Dit e-mailadres is al in gebruik.',
        'error_weak_password': 'Wachtwoord moet minimaal 6 tekens lang zijn.',
        'error_fill_current_step': 'Vul alle velden van deze stap in.',
        'error_select_subjects_register': 'Selecteer ten minste één vak.',
        'error_fill_all_fields': 'Vul alle velden in.',
        'error_enter_email_for_reset': 'Voer je e-mailadres in om je wachtwoord opnieuw in te stellen.',
        'password_reset_sent': 'Een e-mail voor het opnieuw instellen van je wachtwoord is verzonden naar {email}.',
        'your_name': 'Jouw naam',
        'placeholder_name': 'bv. Jan Jansen',
        'email_address': 'E-mailadres',
        'placeholder_email': 'jouw@email.com',
        'placeholder_password': '••••••••',
        'school_name': 'Naam school',
        'class_name': 'Klas',
        'education_level': 'Onderwijsniveau',
        'select_level': 'Selecteer je niveau',
        'select_subjects': 'Selecteer je vakken',
        'select_your_avatar': 'Kies je avatar',
        'customize_ai_title': 'Personaliseer je AI Assistent',
        'bot_name_placeholder': 'Naam van je AI Bot',
        'select_bot_avatar': 'Kies een avatar voor je bot',
        'back_button': 'Terug',
        'next_button': 'Volgende',
        'saving': 'Opslaan...',
        'register_account': 'Account aanmaken',
        'register_title': 'Registreren',
        'login_title': 'Inloggen',
        'login_button': 'Inloggen',
        'login_in_progress': 'Inloggen...',
        'already_account': 'Heb je al een account? Log in',
        'no_account_register': 'Nog geen account? Registreer hier',
        'forgot_password': 'Wachtwoord vergeten?',
        'success_registration': 'Registratie succesvol! Controleer je e-mail om je account te verifiëren en log daarna in.',
        'your_subjects': 'Jouw Vakken',
        'search_subjects_placeholder': 'Zoek je vakken...',
        'profile_incomplete_message': 'Je hebt nog geen vakken geselecteerd.',
        'go_to_settings_message': 'Ga naar instellingen om je profiel compleet te maken.',
        'todays_agenda_title': "Agenda van vandaag",
        'no_events_today': 'Geen evenementen voor vandaag.',
        'go_to_calendar': 'Ga naar de volledige agenda',
        'recent_files_title': 'Recente Bestanden',
        'recent_activities_title': 'Recente Activiteiten',
        'no_recent_files': 'Nog geen bestanden geüpload.',
        'no_recent_activity': 'Nog geen recente activiteit.',
        'view_button': 'Bekijk',
        'error_guest_action_not_allowed': 'Gasten kunnen deze actie niet uitvoeren.',
        'error_enter_file_title': 'Voer een titel in voor het bestand.',
        'error_select_file_to_upload': 'Selecteer een bestand om te uploaden.',
        'success_file_added': 'Bestand succesvol toegevoegd.',
        'error_add_file_failed': 'Kon bestand niet toevoegen: {message}',
        'error_select_files_delete': 'Selecteer bestanden om te verwijderen.',
        'confirm_delete_files': 'Weet je zeker dat je {count} bestand(en) wilt verwijderen?',
        'success_files_deleted': 'Bestand(en) succesvol verwijderd.',
        'error_delete_file_failed': 'Kon bestand niet verwijderen: {message}',
        'back_to_subjects': 'Terug naar vakken',
        'share_button': 'Delen',
        'add_file_section_title': 'Nieuw bestand toevoegen',
        'file_title_placeholder': 'Titel van het bestand',
        'file_description_placeholder': 'Beschrijving (optioneel)',
        'uploading': 'Uploaden...',
        'add_file_button': 'Bestand toevoegen',
        'admin_search_placeholder': 'Zoek op naam of e-mail...',
        'select_files_button': 'Selecteren',
        'no_files_found': 'Geen bestanden gevonden voor dit vak.',
        'calendar_title': 'Agenda',
        'today': 'Vandaag',
        'add_event': 'Nieuw',
        'no_events_day': 'Geen afspraken op deze dag.',
        'edit_event': 'Afspraak bewerken',
        'event_title': 'Titel',
        'event_description': 'Beschrijving (optioneel)',
        'event_test': 'Toets',
        'event_presentation': 'Presentatie',
        'event_homework': 'Huiswerk',
        'event_oral': 'Mondeling',
        'event_other': 'Anders',
        'event_work': 'Werk',
        'event_school': 'School',
        'event_study_plan': 'Studietaak',
        'save_note_button': 'Opslaan',
        'add_event_button': 'Toevoegen',
        'event_subject': 'Vak',
        'event_type': 'Type',
        'delete_event_confirm': 'Weet je zeker dat je "{title}" wilt verwijderen?',
        'success_event_updated': 'Afspraak succesvol bijgewerkt.',
        'success_event_added': 'Afspraak succesvol toegevoegd.',
        'settings_title': 'Instellingen',
        'settings_account_section': 'Account',
        'settings_appearance_section': 'Weergave',
        'settings_privacy_section': 'Privacy & Gegevens',
        'settings_help_info_section': 'Help & Info',
        'profile_section': 'Profiel',
        'profile_picture_current': 'Huidige profielfoto',
        'profile_picture_upload_label': 'Wijzig je profielfoto',
        'change_avatar_button': 'Avatar wijzigen',
        'add_custom_subject': 'Eigen vak toevoegen',
        'custom_subject_placeholder': 'Naam van je vak',
        'error_subject_empty': 'Vaknaam mag niet leeg zijn.',
        'error_subject_exists': 'Dit vak bestaat al.',
        'confirm_remove_subjects_warning': 'Als je vakken deselecteert, worden gerelateerde gegevens zoals bestanden en notities mogelijk niet meer weergegeven. Weet je het zeker?',
        'success_settings_saved': 'Instellingen succesvol opgeslagen.',
        'save_profile_info_button': 'Profiel opslaan',
        'password_reset_section_title': 'Wachtwoord opnieuw instellen',
        'password_reset_section_description': 'Stuur een e-mail naar {email} met instructies om je wachtwoord opnieuw in te stellen.',
        'send_reset_email_button': 'Stuur reset e-mail',
        'error_password_reset_failed': 'Kon wachtwoord reset e-mail niet versturen.',
        'danger_zone_title': 'Gegevensbeheer',
        'cleanup_account_section_title': 'Accountgegevens opschonen',
        'cleanup_account_section_description': 'Dit verwijdert al je persoonlijke gegevens (bestanden, notities, taken, etc.) maar behoudt je account. Deze actie kan niet ongedaan worden gemaakt.',
        'cleanup_account_button': 'Gegevens opschonen',
        'clear_calendar_section_title': 'Agenda leegmaken',
        'clear_calendar_section_description': 'Dit verwijdert permanent alle afspraken uit je agenda. Deze actie kan niet ongedaan worden gemaakt.',
        'clear_calendar_button': 'Agenda leegmaken',
        'delete_account_section_title': 'Account permanent verwijderen',
        'delete_account_section_description': 'Dit zal je account en al je gegevens permanent verwijderen. Deze actie kan niet ongedaan worden gemaakt.',
        'delete_account_button': 'Account verwijderen',
        'choose_theme': 'Kies een thema',
        'font_preference': 'Lettertypevoorkeur',
        'default': 'Standaard',
        'language_preference': 'Taalvoorkeur',
        'dutch': 'Nederlands',
        'english': 'English',
        'home_layout_title': 'Startpagina Indeling',
        'home_layout_description': 'Sleep de widgets om de volgorde op je startpagina aan te passen.',
        'widget_subjects': 'Mijn Vakken',
        'widget_agenda': 'Agenda Vandaag',
        'widget_files': 'Recente Bestanden',
        'notifications_settings_title': 'Notificatie-instellingen',
        'enable_notifications': 'Notificaties inschakelen',
        'privacy_policy_content': 'Jouw privacy is voor ons van het grootste belang. Alle gegevens die je invoert in StudyBox, zoals je bestanden, notities, agenda-items en persoonlijke informatie, worden versleuteld en veilig opgeslagen op onze servers. We gebruiken deze gegevens uitsluitend om de functionaliteit van de app te waarborgen en jouw ervaring te personaliseren. We zullen je gegevens nooit verkopen, delen of op een andere manier openbaar maken aan derden zonder jouw expliciete toestemming. Je hebt te allen tijde de controle over je eigen data en kunt via de gevarenzone-instellingen je gegevens opschonen of je volledige account verwijderen. Voor meer gedetailleerde informatie over ons gegevensbeleid, neem contact met ons op via de support-opties.',
        'app_info': 'Over de app',
        'faq': 'Veelgestelde vragen',
        'version': 'Versie',
        'copyright': 'Alle rechten voorbehouden.',
        'pomodoros': "Pomodoro's",
        'todo_list': 'Takenlijst',
        'flashcards': 'Flashcards',
        'select_a_subject_first': 'Selecteer eerst een vak',
        'sets_for_subject': 'Sets voor {subject}',
        'set_name_placeholder': 'Naam van de nieuwe set',
        'no_sets_found': 'Geen sets gevonden voor dit vak. Maak een nieuwe aan!',
        'no_subjects_flashcards': 'Je hebt nog geen vakken voor je flashcards.',
        'go_to_settings_flashcards': 'Ga naar instellingen om vakken toe te voegen en te beginnen!',
        'cards_in_set': '{count} kaarten',
        'manage_cards': 'Beheren',
        'choose_study_mode': 'Kies een studeermodus',
        'reset_srs_progress': 'Voortgang resetten',
        'study_mode_learn_title': 'Leren (SRS)',
        'study_mode_learn_desc': 'Gebruikt Spaced Repetition om je te helpen efficiënt te leren voor de lange termijn.',
        'study_mode_cram_title': 'Stampen',
        'study_mode_cram_desc': 'Ga snel door alle kaarten heen. Ideaal voor een snelle herhaling vlak voor een toets.',
        'study_mode_mc_title': 'Multiple Choice',
        'study_mode_mc_desc': 'Test je kennis met meerkeuzevragen, willekeurig gegenereerd uit je set.',
        'study_mode_vocab_title': 'Woordenlijst',
        'study_mode_vocab_desc': 'Typ zelf het antwoord. De AI controleert op synoniemen en alternatieve correcte antwoorden.',
        'start_session': 'Start sessie',
        'back_to_sets': 'Terug naar sets',
        'add_flashcard': 'Flashcards beheren',
        'question': 'Vraag (voorkant)',
        'answer': 'Antwoord (achterkant)',
        'add_more_rows': '5 rijen toevoegen',
        'flashcard_added_success': 'Flashcards succesvol opgeslagen.',
        'error_empty_flashcard': 'Voer ten minste één vraag en antwoord in.',
        'next_card': 'Volgende kaart',
        'cards_to_go': '{count} te gaan',
        'cards_to_go_counter': '{current} / {total}',
        'show_answer': 'Toon antwoord',
        'feedback_again': 'Opnieuw',
        'feedback_good': 'Goed',
        'no_flashcards_found': 'Geen flashcards gevonden',
        'all_cards_learned_title': 'Alles geleerd!',
        'all_cards_learned_desc': 'Goed gedaan! Je hebt alle kaarten voor deze sessie bestudeerd. Kom later terug voor herhaling.',
        'choose_other_method_button': 'Kies andere modus',
        'reset_and_start_over_button': 'Reset & Herstart',
        'session_complete': 'Sessie voltooid!',
        'your_score': 'Je score: {correct} / {total}',
        'your_grade': 'Jouw Cijfer',
        'well_done_message': 'Goed gedaan! Blijf oefenen.',
        'focus_session': 'Focus',
        'break_session': 'Pauze',
        'Focusing on:': 'Focus op:',
        'no_specific_task_option': 'Geen taak geselecteerd',
        'set_added_success': 'Set succesvol aangemaakt.',
        'confirm_delete_set': 'Weet je zeker dat je de set "{name}" en alle bijbehorende kaarten wilt verwijderen?',
        'set_deleted_success': 'Set succesvol verwijderd.',
        'error_empty_set_name': 'Naam van de set mag niet leeg zijn.',
        'reset_srs_confirm': 'Weet je zeker dat je de leervoortgang (SRS) voor deze set wilt resetten?',
        'error_flashcard_set_min_cards': 'Deze modus vereist minimaal 2 kaarten in de set.',
        'error_vocab_set_min_cards': 'Deze modus vereist minimaal 1 kaart in de set.',
        'loading_cards': 'Kaarten laden...',
        'error_failed_to_load_cards': 'Kon flashcards niet laden.',
        'error_failed_to_load_sets': 'Kon sets niet laden.',
        'all_subjects_option': 'Alle vakken',
        'add_note_button': 'Nieuwe notitie',
        'edit_note': 'Notitie bewerken',
        'add_note_title_placeholder': 'Titel',
        'add_note_content_placeholder': 'Begin hier met typen...',
        'note_updated_success': 'Notitie succesvol bijgewerkt.',
        'note_added_success': 'Notitie succesvol toegevoegd.',
        'error_empty_note_title': 'Titel mag niet leeg zijn.',
        'confirm_delete_note': 'Weet je zeker dat je deze notitie wilt verwijderen?',
        'note_deleted_success': 'Notitie succesvol verwijderd.',
        'set_reminder_title': 'Herinnering instellen voor: {task}',
        'reminder_date': 'Datum',
        'reminder_time': 'Tijd',
        'save_reminder_button': 'Herinnering opslaan',
        'remove_reminder_button': 'Verwijder herinnering',
        'task_reminder_title': 'Taakherinnering',
        'error_failed_to_load_tasks': 'Kon taken niet laden.',
        'add_task_placeholder': 'Voeg een nieuwe taak toe...',
        'add_task_button': 'Toevoegen',
        'no_tasks_found': 'Geen taken gevonden. Voeg er een toe om te beginnen!',
        'task_added_success': 'Taak succesvol toegevoegd.',
        'task_updated_success': 'Taakstatus bijgewerkt.',
        'confirm_delete_task': 'Weet je zeker dat je deze taak wilt verwijderen?',
        'task_deleted_success': 'Taak succesvol verwijderd.',
        'notifications_denied_error': 'Notificaties zijn geblokkeerd. Schakel ze in via je browserinstellingen.',
        'notifications_denied_prompt': 'Je hebt geen toestemming gegeven voor notificaties. De herinnering wordt niet getoond.',
        'error_empty_task': 'Taak mag niet leeg zijn.',
        'grade_calculator_title': 'Cijfercalculator',
        'grade_name_placeholder': 'Naam toets (optioneel)',
        'grade': 'Cijfer',
        'weight': 'Weging (%)',
        'add_grade': 'Cijfer toevoegen',
        'current_average': 'Je huidige gemiddelde:',
        'goal_calculator_title': 'Doelcalculator',
        'desired_average': 'Gewenst gemiddelde',
        'future_exam_weight': 'Weging toekomstige toets (%)',
        'calculate_needed_grade': 'Bereken benodigd cijfer',
        'goal_easy_message': 'Je staat al hoger dan je doel. Goed bezig!',
        'goal_impossible_message': 'Het is wiskundig onmogelijk om je doel te halen. Het hoogst haalbare is...',
        'grade_needed_message': 'Je moet een **{grade}** halen om een **{desired_average}** te staan.',
        'admin_dashboard': 'Admin Dashboard',
        'users': 'Gebruikers',
        'broadcasts': 'Aankondigingen',
        'admin_feedback_dashboard': 'Feedback',
        'loading_data': 'Gegevens laden...',
        'last_login': 'Laatste login',
        'status': 'Status',
        'actions': 'Acties',
        'active': 'Actief',
        'disabled': 'Uitgeschakeld',
        'enable_user': 'Activeer gebruiker',
        'disable_user': 'Deactiveer gebruiker',
        'refresh_data': 'Vernieuwen',
        'confirm_disable_user': 'Weet je zeker dat je gebruiker {name} wilt deactiveren?',
        'confirm_enable_user': 'Weet je zeker dat je gebruiker {name} wilt activeren?',
        'user_status_updated': 'Gebruikersstatus succesvol bijgewerkt.',
        'error_user_status_update': 'Kon gebruikersstatus niet bijwerken.',
        'send_broadcast': 'Aankondiging versturen',
        'broadcast_title_placeholder': 'Titel',
        'broadcast_message_placeholder': 'Typ here je bericht...',
        'sending': 'Verzenden...',
        'send_message_button': 'Verstuur bericht',
        'error_broadcast_empty': 'Titel en bericht mogen niet leeg zijn.',
        'broadcast_success': 'Aankondiging succesvol verstuurd.',
        'error_broadcast_failed': 'Kon aankondiging niet versturen.',
        'past_broadcasts': 'Eerdere aankondigingen',
        'delete_all_broadcasts': 'Alles verwijderen',
        'no_past_broadcasts': 'Geen eerdere aankondigingen.',
        'confirm_delete_all_broadcasts_and_notifications': 'Weet je zeker dat je ALLE aankondigingen en de bijbehorende notificaties voor alle gebruikers wilt verwijderen? Dit kan niet ongedaan worden gemaakt.',
        'all_broadcasts_deleted': 'Alle aankondigingen en notificaties zijn verwijderd.',
        'error_deletion_failed': 'Verwijderen mislukt.',
        'from': 'Van',
        'submitted_on': 'Ingediend op',
        'status_new': 'Nieuw',
        'status_replied': 'Beantwoord',
        'reply_to_feedback': 'Antwoord op feedback',
        'your_reply_placeholder': 'Typ je antwoord...',
        'send_reply_button': 'Verstuur antwoord',
        'reply_sent_success': 'Antwoord succesvol verstuurd.',
        'error_reply_failed': 'Kon antwoord niet versturen.',
        'admin_select_feedback': 'Selecteer een feedbackbericht om de details te bekijken en te beantwoorden.',
        'admin_streak_leaderboard': 'Streak Leaderboard',
        'no_streak_users': 'Geen gebruikers met een actieve streak.',
        'admin_appearance_settings': 'Weergave Instellingen (Admin)',
        'admin_security_settings': 'Beveiligingsinstellingen',
        'admin_pin_toggle_label': 'PIN-beveiliging bij opstarten inschakelen',
        'admin_pin_verify_title': 'PIN verificatie',
        'admin_pin_verify_desc': 'Om deze instelling te wijzigen, moet je de beveiligingsvraag beantwoorden.',
        'admin_pin_answer_placeholder': 'Jouw antwoord',
        'admin_pin_error_incorrect': 'Incorrect antwoord.',
        'no_avatar_option': 'Geen avatar',
        'avatar_selection_title': 'Kies je avatar',
        'save_avatar_button': 'Opslaan',
        'back': 'Terug',
        'mark_all_as_read': 'Markeer alles als gelezen',
        'confirm_clear_all_notifications': 'Weet je zeker dat je alle notificaties wilt verwijderen?',
        'content_per_subject': 'Inhoud per vak',
        'notifications_cleared': 'Notificaties gewist.',
        'no_notifications': 'Je hebt geen nieuwe notificaties.',
        'no_notifications_disabled_title': 'Notificaties zijn uitgeschakeld',
        'no_notifications_disabled_text': 'Je ontvangt geen meldingen. Je kunt dit wijzigen in de instellingen.',
        'intro_step1_title': 'Welkom bij StudyBox!',
        'intro_step1_text': 'Jouw persoonlijke assistent voor school. Organiseer je bestanden, agenda en notities op één plek.',
        'intro_step2_title': 'Beheer je Agenda',
        'intro_step2_text': 'Voeg toetsen, huiswerk en deadlines toe. Mis nooit meer een belangrijke datum!',
        'intro_step3_title': 'Krachtige Tools',
        'intro_step3_text': 'Maak flashcards met slimme herhalingen (SRS), schrijf notities, gebruik de Pomodoro-timer en laat de AI zelfs een heel studieplan voor je maken!',
        'intro_step4_title': 'Maak het Jouw Stijl',
        'intro_step4_text': 'Kies je eigen kleurenthema en lettertype. Maak van StudyBox jouw persoonlijke studie-omgeving.',
        'intro_step5_title': 'Klaar om te Starten!',
        'intro_step5_text': 'Je bent er helemaal klaar voor. Laten we beginnen met het organiseren van je succes!',
        'intro_finish_button': 'Aan de slag!',
        'ai_chat_welcome': 'Hoi {userName}! Ik ben {botName}, je persoonlijke studie-assistent. Hoe kan ik je vandaag helpen?',
        'ai_chat_placeholder': 'Stel een vraag aan {botName}...',
        'study_planner': 'Studieplanner',
        'study_planner_title': 'Studieplanner',
        'plan_for_date': 'Test op {date}',
        'registration_goal_title': 'Wat is je hoofddoel?',
        'registration_almost_there': 'Bijna klaar!',
        'goal_higher_grades': 'Hogere cijfers halen',
        'goal_be_organized': 'Georganiseerd blijven',
        'goal_better_planning': 'Beter plannen',
        'goal_less_stress': 'Minder stress',
        'hours': 'uur',
        'in_progress_badge': ' bezig ',
        'activity_type_file': 'Bestand',
        'activity_type_note': 'Notitie',
        'activity_type_plan': 'Plan',
        'activity_type_set': 'Flashcards',
        'tasks_completed': 'Taken voltooid (deze week)',
        'study_time_minutes': 'Studieminuten (deze week)',
        'flashcards_created': 'Nieuwe sets (deze week)',
        'todays_events': 'Afspraken vandaag',
        'flashcard_ai_modal_title': 'Genereer met AI',
        'flashcard_ai_modal_desc': 'Plak je notities of een tekst hieronder en de AI maakt er automatisch flashcards van.',
        'flashcard_ai_topic_placeholder': 'Onderwerp (bv. Franse Revolutie)',
        'flashcard_ai_placeholder': 'Plak hier je tekst...',
        'generate_button': 'Genereer',
        'flashcards_creating_message': 'Flashcards worden gemaakt...',
        'ai_checking_answer': 'Controleren...',
        'submit_answer': 'Controleer antwoord',
        'ai_feedback_correct': 'Correct!',
        'ai_feedback_incorrect': 'Helaas, het juiste antwoord was: {correct_answer}',
        'session_summary_title': 'Sessie Samenvatting',
        'stars_earned_title': 'Verdiende Sterren!',
        'correct_answers': 'Correct',
        'incorrect_answers': 'Incorrect',
        'time_spent': 'Tijd',
        'new_set_name_prompt': 'Geef een naam voor de nieuwe set met foute antwoorden:',
        'practice_incorrect': 'Oefen foute antwoorden',
        'new_set_created_success': 'Nieuwe set "{name}" succesvol aangemaakt!',
        'no_incorrect_answers': 'Geen foute antwoorden om te oefenen!',
        'create_set_from_incorrect': 'Maak set van foute antwoorden',
        'correct_answer': 'Correct antwoord',
        'your_answer': 'Jouw antwoord',
        'exit_session_confirm': 'Weet je zeker dat je de sessie wilt beëindigen? Je voortgang gaat verloren.',
        'error_select_min_two_sets': 'Selecteer minimaal twee sets om te combineren.',
        'combined_set_name': 'Gecombineerde Set ({count})',
        'shared_by': 'Gedeeld door {name}',
        'ai_no_events_found': 'De AI kon geen duidelijke afspraken vinden in de tekst.',
        'ai_parsing_error': 'Er is een fout opgetreden bij het analyseren van de tekst. Probeer het opnieuw.',
        'analyzing': 'Analyseren...',
        'analyze_button': 'Analyseer Tekst',
        'review_schedule': 'Controleer het rooster',
        'import_for_weeks': 'Importeer voor',
        'weeks': 'weken',
        'edit_text_button': 'Tekst aanpassen',
        'importing': 'Importeren...',
        'import_button': 'Importeer',
        'import_success': '{count} afspraken succesvol geïmporteerd!',
        'import_error': 'Importeren mislukt.',
        'download_agenda': 'Agenda Downloaden',
        'download_weeks_label': 'Downloaden voor de komende',
        'download_format_label': 'Kies een formaat',
        'downloading_and_started': 'Downloaden...',
        'download_button': 'Download',
        'sync_calendar_title': 'Synchroniseer je Agenda',
        'sync_calendar_desc': 'Synchroniseer externe agenda\'s (zoals schoolroosters) via een iCal-link.',
        'get_ical_link': 'Vind je iCal-link',
        'how_to_get_link': 'Klik op je provider voor een handleiding:',
        'paste_ical_link': 'Plak je iCal-link',
        'calendar_name': 'Naam van agenda (bv. Schoolrooster)',
        'select_provider': 'Selecteer provider',
        'calendar_url': 'Plak hier de iCal-link (webcal:// of https://)',
        'save_calendar': 'Agenda opslaan',
        'synced_calendars': 'Gesynchroniseerde Agenda\'s',
        'no_synced_calendars': 'Nog geen agenda\'s gesynchroniseerd.',
        'sync_calendar_tutorial_google': 'https://support.google.com/calendar/answer/37648?hl=nl',
        'sync_calendar_tutorial_apple': 'https://support.apple.com/nl-nl/guide/calendar/icl1022/mac',
        'sync_calendar_tutorial_teams': 'https://support.microsoft.com/nl-nl/office/een-kanaalagenda-weergeven-in-microsoft-teams-5203f61a-03e5-45a8-b636-121087278278',
        'sync_calendar_tutorial_canvas': 'https://community.canvaslms.com/t5/Student-Guide/How-do-I-subscribe-to-the-Calendar-feed-using-Google-Calendar/ta-p/413',
        'sync_calendar_tutorial_magister': 'https://www.google.com/search?q=magister+agenda+ical+link',
        'settings_sync_calendar': 'Synchroniseren',
        'weekly_overview': 'Weekoverzicht',
        'planner_task': 'Studietaak',
        'planner_tip': 'Tip',
        'error_all_fields_required': 'Vul alle verplichte velden in.',
        'planner_create_your_schedule': 'Maak je studieplan',
        'planner_select_subject': 'Kies een vak',
        'planner_topic_placeholder': 'Onderwerp(en) van de toets',
        'planner_amount_placeholder': 'Hoeveelheid leerstof (bv. H1-H3)',
        'planner_generating': 'Genereren...',
        'planner_generate_button': 'Genereer Plan',
        'planner_error_text': 'De AI kon geen planning maken. Probeer de invoer duidelijker te maken of controleer je bestaande agenda op conflicten.',
        'planner_error_title': 'Oeps, er ging iets mis!',
        'planner_result_title': 'Jouw Studieplan voor {subject}',
        'planner_start_over': 'Opnieuw beginnen',
        'create_new_plan': 'Nieuw Plan Maken',
        'plan_title_placeholder': 'Naam van je plan (bv. Geschiedenis Toetsweek)',
        'subject': 'Vak',
        'add_subject_button': 'Vak toevoegen',
        'plan_test_date': 'Datum van de toets',
        'creating_plan': 'Plan maken...',
        'plan_created_success': 'Studieplan succesvol aangemaakt en toegevoegd aan je agenda!',
        'delete_plan_confirm': 'Weet je zeker dat je dit plan wilt verwijderen?',
        'plan_deleted_success': 'Plan succesvol verwijderd.',
        'select_all_button': 'Selecteer alles',
        'delete_selected_button': 'Verwijder',
        'confirm_delete_plans': 'Weet je zeker dat je {count} plannen wilt verwijderen?',
        'error_share_invalid_email': 'Voer een geldig e-mailadres in.',
        'error_cannot_share_with_self': 'Je kunt niet met jezelf delen.',
        'error_user_not_found': 'Geen gebruiker gevonden met e-mail: {email}.',
        'share_plan_success': 'Plan succesvol gedeeld met {email}!',
        'error_share_plan_failed': 'Delen van plan mislukt.',
        'share_plan_title': 'Deel "{title}"',
        'share_with_email': 'Deel met e-mailadres',
        'share_set_title': 'Deel set "{name}"',
        'share_success': 'Set succesvol gedeeld met {email}!',
        'error_share_failed': 'Delen mislukt.',
        'verify_user_button': 'Verifieer gebruiker handmatig',
        'confirm_verify_user': 'Weet je zeker dat je {name} handmatig wilt verifiëren?',
        'user_verified_success': 'Gebruiker succesvol geverifieerd.',
        'error_user_verify_failed': 'Verifiëren van gebruiker mislukt.',
        'feedback_title': 'Feedback & Support',
        'feedback_subtitle': 'Heb je een vraag, suggestie of een bug gevonden? Laat het ons weten!',
        'feedback_subject_placeholder': 'Onderwerp',
        'feedback_message_placeholder': 'Jouw bericht...',
        'feedback_sent_success': 'Feedback succesvol verstuurd. Bedankt!',
        'error_feedback_failed': 'Versturen van feedback mislukt.',
        'send_feedback_button': 'Verstuur Feedback',
        'your_feedback_history': 'Jouw Feedbackgeschiedenis',
        'no_feedback_history': 'Je hebt nog geen feedback verstuurd.',
        'new_chat': 'Nieuwe Chat',
        'chat_history_title': 'Chatgeschiedenis',
        'verify_email_title': 'Verifieer je e-mailadres',
        'verify_email_instructions': 'We hebben een verificatielink gestuurd naar {email}. Klik op de link in de e-mail om je account te activeren.',
        'verify_email_spam_check': 'Geen e-mail ontvangen? Controleer je spamfolder.',
        'verify_email_continue_button': 'Ik heb mijn e-mail geverifieerd',
        'email_sent': 'E-mail verzonden!',
        'verify_email_resend_button': 'Stuur opnieuw',
        'no_plans_yet': 'Nog geen studieplannen.',
        'no_plans_cta': 'Laat de AI een plan voor je maken!',
        'error_ai_check_failed': 'AI-controle mislukt, controleer handmatig.',
        'items': 'items',
        'no_data_for_chart': 'Geen gegevens voor deze grafiek.',
        'event_type_distribution': 'Verdeling agendapunten',
        'progress': 'Voortgang',
        'time_spent_per_subject': 'Tijd besteed per vak',
        'total_items': 'Totaal aantal items',
        'total_study_time': 'Totale studietijd'
    },
    en: {
        'confirm_delete_all_chats': 'Are you sure you want to delete ALL chat conversations? This cannot be undone.',
        'all_chats_deleted_success': 'All chats have been successfully deleted.',
        'error_delete_all_chats_failed': 'Could not delete chats.',
        'delete_all_button': 'Delete All',
        'notification_note_share_title': 'Note Shared With You',
        'notification_note_share_text': '{name} has shared the note "{noteTitle}" with you.',
        'share_note_title': 'Share note "{title}"',
        'share_note_success': 'Note successfully shared with {email}!',
        'error_share_note_failed': 'Failed to share note.',
        'incoming_shared_notes': 'Incoming Shared Notes',
        'accept_note_success': 'Successfully accepted note "{title}"!',
        'error_accept_note_failed': 'Failed to accept note.',
        'accept_button': 'Accept',
        'confirm_delete_chat': 'Are you sure you want to delete this chat? This cannot be undone.',
        'chat_deleted_success': 'Chat successfully deleted.',
        'ai_importer_title': 'Import Schedule with AI',
        'ai_importer_description': 'Paste your schedule (or any other text with appointments) below. The AI will try to recognize the events and schedule them for you.',
        'delete_study_plan_from_ai_confirm': 'The AI wants to delete the study plan "{title}". Are you sure?',
        'delete_study_plan_from_ai_success': 'Successfully deleted study plan "{title}".',
        'delete_study_plan_from_ai_fail': 'Failed to delete study plan "{title}".',
        'delete_study_plan_from_ai_not_found': 'Could not find study plan "{title}".',
        'add_button': 'Add',
        'confirm_delete_user': 'Are you sure you want to permanently delete {name} and all their data? This action cannot be undone.',
        'deleting_user_progress': 'Deleting {name}...',
        'user_deleted_success': '{name} has been successfully deleted.',
        'user_deleted_fail': 'Failed to delete {name}.',
        'error_email_in_use_admin_contact': 'This email address is already in use. Please contact an administrator if you believe this is an error.',
        'admin_pin_secret_question_1': 'On what day was StudyBox created?',
        'admin_pin_secret_question_2': "What was StudyBox's first name?",
        'confirm_delete_feedback': 'Are you sure you want to delete this feedback message and all its replies?',
        'feedback_deleted': 'Feedback successfully deleted.',
        'add_stars': 'Manage Stars',
        'stars_to_add': 'Number of stars (+/-)',
        'stars_added_success': '{count} stars updated successfully.',
        'stars_added_fail': 'Failed to update stars.',
        'update_stars_button': 'Update Stars',
        'user_stats': 'User Stats',
        'total_stars': 'Total Stars',
        'ai_system_instruction': 'You are {botName}, a friendly and super-intelligent assistant for {userName}. You can help with study questions about the subjects {subjects}, create summaries, manage the user\'s calendar, and answer general knowledge questions. Today\'s date is {todayDate}. If asked who created you, answer: "I was created by the StudyBox developers." Always be helpful, positive, and a bit playful. Always answer in English, unless the user explicitly asks you to answer in another language.',
        'generate_with_mimi': 'Ask {botName}',
        'ai_generate_notes_title_mimi': 'Generate notes with {botName}',
        'welcome_notification_title': 'Welcome to StudyBox! 🎉',
        'welcome_notification_text': 'Welcome, {name}! We\'re glad you\'re here. StudyBox is designed to make your school life easier. Dive into the Calendar to track your deadlines, create Flashcards in the Tools section, or chat with your personal AI Assistant for help. Happy studying!',
        'send_as_studybox': 'Send as \'StudyBox\'',
        'ai_title_generation_prompt': 'Summarize the following conversation in 5 words or less to use as a title. The conversation is between a user and a study assistant. Focus on the main topic. Reply ONLY with the title itself, without any extra text or quotes. Conversation:\n\n',
        'haptics_feedback_title': 'Haptic Feedback',
        'haptics_feedback_description': 'Enable a light vibration for important actions like completing a task.',
        'search_my_files': 'Search my files...',
        'my_files_tab': 'My Files',
        'discover_files': 'Discover',
        'page_count': 'Page count: {count}',
        'preview_not_available': 'Preview not available for this file type.',
        'chat_with_user': 'Chat with {name}',
        'type_a_message': 'Type a message...',
        'no_messages_yet': 'No messages yet. Say hello!',
        'view_all_by_uploader': 'View all by {name}',
        'showing_files_by': 'Files by {name}',
        'show_all_files': 'Show all files',
        'file_preview': 'File Preview',
        'marketplace_title': 'Marketplace',
        'filter_by_subject': 'Filter by subject',
        'sort_by': 'Sort by',
        'sort_newest': 'Newest',
        'sort_popular': 'Most Popular',
        'sort_rating': 'Highest Rating',
        'search_marketplace_placeholder': 'Search summaries, tests...',
        'price_range': 'Price',
        'free': 'Free',
        'paid': 'Paid',
        'home_dashboard': 'Dashboard',
        'upload_type': 'Upload Type',
        'public_share': 'Public Share',
        'public_share_desc': 'File is visible in Discover and you can earn stars.',
        'private_upload': 'Private Storage',
        'private_upload_desc': 'File is only visible to you.',
        'marketplace': 'Discover',
        'star_price': 'Price in stars',
        'download_for_stars': 'Download ({price} {stars})',
        'stars_currency': 'stars',
        'not_enough_stars': 'You don\'t have enough stars to download this file.',
        'confirm_purchase_file': 'Are you sure you want to purchase "{title}" for {price} stars?',
        'purchase_success': 'Purchase successful! The file will now open.',
        'error_purchase_failed': 'Purchase failed. Please try again.',
        'rating': 'Rating',
        'downloads': 'Downloads',
        'by_uploader': 'by {name}',
        'owned': 'Owned',
        'your_file': 'Your File',
        'rate_file': 'Rate this file',
        'no_files_in_marketplace': 'No files have been shared yet. Be the first!',
        'select_subject_to_discover': 'Select a subject to discover files',
        'uploader': 'Uploader',
        'description': 'Description',
        'send_message': 'Send Message',
        'view_profile_coming_soon': 'User profiles and the ability to send messages are coming soon!',
        'purchase_and_download': 'Purchase & Download',
        'tasks_for_today': 'Tasks for today',
        'due_date': 'Due date',
        'recurring_daily': 'Recurring daily',
        'no_tasks_for_today': 'No tasks for today. Great job!',
        'todo_daily_refresh_note': 'The list refreshes daily. Completed daily tasks will reappear.',
        'error_reauth_failed': 'Reauthentication failed. Please check your password.',
        'reauth_modal_title': 'Authentication Required',
        'reauth_modal_description': 'Please enter your password again to continue.',
        'password': 'Password',
        'cancel_button': 'Cancel',
        'confirm_delete_account_button': 'Yes, delete account',
        'reauth_modal_title_cleanup': 'Confirm Account Cleanup',
        'reauth_modal_description_cleanup': 'Enter your password to confirm you want to delete all your data.',
        'confirm_cleanup_account_button': 'Yes, clean up data',
        'reauth_modal_title_clear_calendar': 'Confirm Clear Calendar',
        'reauth_modal_description_clear_calendar': 'Enter your password to confirm you want to delete all calendar items.',
        'confirm_clear_calendar_button': 'Yes, clear calendar',
        'clear_calendar_progress': 'Clearing your calendar...',
        'success_calendar_cleared': 'Your calendar has been successfully cleared.',
        'error_calendar_clear_failed': 'Failed to clear the calendar.',
        'app_back_online_message': 'You are back online.',
        'app_offline_message': 'You are currently offline.',
        'confirm_logout': 'Are you sure you want to log out?',
        'error_save_settings_failed': 'Could not save settings.',
        'error_failed_to_save_admin_settings': 'Could not save admin settings.',
        'profile_picture_upload_success': 'Profile picture updated successfully.',
        'error_profile_pic_upload_failed': 'Could not upload profile picture.',
        'cleanup_account_progress': 'Cleaning up your account data...',
        'success_account_cleaned': 'Your account data has been successfully cleaned up.',
        'error_account_cleanup_failed': 'Account cleanup failed.',
        'deleting_account_progress': 'Deleting account...',
        'success_account_deleted': 'Your account has been successfully deleted.',
        'error_account_deletion_failed': 'Account deletion failed.',
        'error_admin_login_failed': 'Admin login failed.',
        'guest_fallback_name': 'Guest',
        'error_account_disabled': 'Account deactivated by administrator. Contact the administrator.',
        'streak_lost_notification_title': 'Streak Lost!',
        'streak_lost_notification_text': 'You had a streak of {count} days. Start a new one today!',
        'error_profile_load_failed': 'Could not load your profile.',
        'success_logout': 'You have been successfully logged out.',
        'share_link_copied': 'Link for "{title}" copied!',
        'error_copy_share_link': 'Could not copy the link.',
        'notifications_title': 'Notifications',
        'logout_button': 'Log Out',
        'focus_session_complete': 'Focus session complete! Time for a break.',
        'break_session_complete': 'Break is over! Time to focus.',
        'feedback_reply_notification_title': 'Reply to your feedback',
        'feedback_reply_notification_text': 'You have received a reply to your feedback about "{subject}".',
        'notification_plan_share_title': 'Plan Shared With You',
        'notification_plan_share_text': '{name} shared the plan "{planName}" with you.',
        'notification_flashcard_share_title': 'Flashcards Shared With You',
        'notification_flashcard_share_text': '{name} shared the set "{setName}" ({subject}) with you.',
        'confirm_button': 'Confirm',
        'close_button': 'Close',
        'calendar': 'Calendar',
        'extra_tools': 'Extra Tools',
        'settings': 'Settings',
        'feedback_support': 'Feedback & Support',
        'welcome_message': 'Welcome, {name}!',
        'streak_days': '{count} day streak',
        'my_subjects': 'My Subjects',
        'my_files': 'My Files',
        'notes': 'Notes',
        'error_unknown': 'An unknown error occurred.',
        'error_invalid_email': 'Invalid email address.',
        'error_invalid_credentials': 'Invalid credentials.',
        'error_email_in_use': 'This email address is already in use.',
        'error_weak_password': 'Password must be at least 6 characters long.',
        'error_fill_current_step': 'Please fill in all fields for this step.',
        'error_select_subjects_register': 'Please select at least one subject.',
        'error_fill_all_fields': 'Please fill in all fields.',
        'error_enter_email_for_reset': 'Enter your email address to reset your password.',
        'password_reset_sent': 'A password reset email has been sent to {email}.',
        'your_name': 'Your Name',
        'placeholder_name': 'e.g. John Doe',
        'email_address': 'Email Address',
        'placeholder_email': 'your@email.com',
        'placeholder_password': '••••••••',
        'school_name': 'School Name',
        'class_name': 'Class',
        'education_level': 'Education Level',
        'select_level': 'Select your level',
        'select_subjects': 'Select your subjects',
        'select_your_avatar': 'Choose your avatar',
        'customize_ai_title': 'Personalize your AI Assistant',
        'bot_name_placeholder': 'Name of your AI Bot',
        'select_bot_avatar': 'Choose an avatar for your bot',
        'back_button': 'Back',
        'next_button': 'Next',
        'saving': 'Saving...',
        'register_account': 'Create Account',
        'register_title': 'Register',
        'login_title': 'Log In',
        'login_button': 'Log In',
        'login_in_progress': 'Logging in...',
        'already_account': 'Already have an account? Log in',
        'no_account_register': 'No account yet? Register here',
        'forgot_password': 'Forgot password?',
        'success_registration': 'Registration successful! Check your email to verify your account, then log in.',
        'your_subjects': 'Your Subjects',
        'search_subjects_placeholder': 'Search your subjects...',
        'profile_incomplete_message': 'You haven\'t selected any subjects yet.',
        'go_to_settings_message': 'Go to settings to complete your profile.',
        'todays_agenda_title': "Today's Agenda",
        'no_events_today': 'No events for today.',
        'go_to_calendar': 'Go to the full calendar',
        'recent_files_title': 'Recent Files',
        'recent_activities_title': 'Recent Activities',
        'no_recent_files': 'No files uploaded yet.',
        'no_recent_activity': 'No recent activity yet.',
        'view_button': 'View',
        'error_guest_action_not_allowed': 'Guests cannot perform this action.',
        'error_enter_file_title': 'Please enter a title for the file.',
        'error_select_file_to_upload': 'Please select a file to upload.',
        'success_file_added': 'File added successfully.',
        'error_add_file_failed': 'Could not add file: {message}',
        'error_select_files_delete': 'Select files to delete.',
        'confirm_delete_files': 'Are you sure you want to delete {count} file(s)?',
        'success_files_deleted': 'File(s) deleted successfully.',
        'error_delete_file_failed': 'Could not delete file: {message}',
        'back_to_subjects': 'Back to subjects',
        'share_button': 'Share',
        'add_file_section_title': 'Add New File',
        'file_title_placeholder': 'Title of the file',
        'file_description_placeholder': 'Description (optional)',
        'uploading': 'Uploading...',
        'add_file_button': 'Add File',
        'admin_search_placeholder': 'Search by name or email...',
        'select_files_button': 'Select',
        'no_files_found': 'No files found for this subject.',
        'calendar_title': 'Calendar',
        'today': 'Today',
        'add_event': 'New',
        'no_events_day': 'No appointments on this day.',
        'edit_event': 'Edit Event',
        'event_title': 'Title',
        'event_description': 'Description (optional)',
        'event_test': 'Test',
        'event_presentation': 'Presentation',
        'event_homework': 'Homework',
        'event_oral': 'Oral Exam',
        'event_other': 'Other',
        'event_work': 'Work',
        'event_school': 'School',
        'event_study_plan': 'Study Plan Task',
        'save_note_button': 'Save',
        'add_event_button': 'Add',
        'event_subject': 'Subject',
        'event_type': 'Type',
        'delete_event_confirm': 'Are you sure you want to delete "{title}"?',
        'success_event_updated': 'Event updated successfully.',
        'success_event_added': 'Event added successfully.',
        'settings_title': 'Settings',
        'settings_account_section': 'Account',
        'settings_appearance_section': 'Appearance',
        'settings_privacy_section': 'Privacy & Data',
        'settings_help_info_section': 'Help & Info',
        'profile_section': 'Profile',
        'profile_picture_current': 'Current profile picture',
        'profile_picture_upload_label': 'Change your profile picture',
        'change_avatar_button': 'Change Avatar',
        'add_custom_subject': 'Add custom subject',
        'custom_subject_placeholder': 'Name of your subject',
        'error_subject_empty': 'Subject name cannot be empty.',
        'error_subject_exists': 'This subject already exists.',
        'confirm_remove_subjects_warning': 'If you deselect subjects, related data like files and notes might no longer be displayed. Are you sure?',
        'success_settings_saved': 'Settings saved successfully.',
        'save_profile_info_button': 'Save Profile',
        'password_reset_section_title': 'Password Reset',
        'password_reset_section_description': 'Send an email to {email} with instructions to reset your password.',
        'send_reset_email_button': 'Send Reset Email',
        'error_password_reset_failed': 'Could not send password reset email.',
        'danger_zone_title': 'Data Management',
        'cleanup_account_section_title': 'Clean Up Account Data',
        'cleanup_account_section_description': 'This will remove all your personal data (files, notes, tasks, etc.) but keep your account. This action cannot be undone.',
        'cleanup_account_button': 'Clean Up Data',
        'clear_calendar_section_title': 'Clear Calendar',
        'clear_calendar_section_description': 'This will permanently delete all events from your calendar. This action cannot be undone.',
        'clear_calendar_button': 'Clear Calendar',
        'delete_account_section_title': 'Permanently Delete Account',
        'delete_account_section_description': 'This will permanently delete your account and all your data. This action cannot be undone.',
        'delete_account_button': 'Delete Account',
        'choose_theme': 'Choose a theme',
        'font_preference': 'Font Preference',
        'default': 'Default',
        'language_preference': 'Language Preference',
        'dutch': 'Nederlands',
        'english': 'English',
        'home_layout_title': 'Homepage Layout',
        'home_layout_description': 'Drag and drop the widgets to rearrange the order on your homepage.',
        'widget_subjects': 'My Subjects',
        'widget_agenda': 'Today\'s Agenda',
        'widget_files': 'Recent Files',
        'notifications_settings_title': 'Notification Settings',
        'enable_notifications': 'Enable notifications',
        'privacy_policy_content': 'Your privacy is of utmost importance to us. All data you enter into StudyBox, such as your files, notes, calendar items, and personal information, is encrypted and securely stored on our servers. We use this data solely to ensure the app\'s functionality and to personalize your experience. We will never sell, share, or otherwise disclose your data to third parties without your explicit consent. You have control over your own data at all times and can clean up your data or delete your entire account via the danger zone settings. for more detailed information about our data policy, please contact us via the support options.',
        'app_info': 'About the App',
        'faq': 'Frequently Asked Questions',
        'version': 'Version',
        'copyright': 'All rights reserved.',
        'pomodoros': 'Pomodoros',
        'todo_list': 'To-Do List',
        'flashcards': 'Flashcards',
        'select_a_subject_first': 'Select a subject first',
        'sets_for_subject': 'Sets for {subject}',
        'set_name_placeholder': 'Name of the new set',
        'no_sets_found': 'No sets found for this subject. Create a new one!',
        'no_subjects_flashcards': 'You don\'t have any subjects for your flashcards yet.',
        'go_to_settings_flashcards': 'Go to settings to add subjects and get started!',
        'cards_in_set': '{count} cards',
        'manage_cards': 'Manage',
        'choose_study_mode': 'Choose a study mode',
        'reset_srs_progress': 'Reset progress',
        'study_mode_learn_title': 'Learn (SRS)',
        'study_mode_learn_desc': 'Uses Spaced Repetition to help you learn efficiently for the long term.',
        'study_mode_cram_title': 'Cram',
        'study_mode_cram_desc': 'Quickly go through all cards. Ideal for a quick review right before a test.',
        'study_mode_mc_title': 'Multiple Choice',
        'study_mode_mc_desc': 'Test your knowledge with multiple choice questions, randomly generated from your set.',
        'study_mode_vocab_title': 'Vocabulary',
        'study_mode_vocab_desc': 'Type the answer yourself. The AI checks for synonyms and alternative correct answers.',
        'start_session': 'Start Session',
        'back_to_sets': 'Back to sets',
        'add_flashcard': 'Manage Flashcards',
        'question': 'Question (front)',
        'answer': 'Answer (back)',
        'add_more_rows': 'Add 5 rows',
        'flashcard_added_success': 'Flashcards saved successfully.',
        'error_empty_flashcard': 'Please enter at least one question and answer.',
        'next_card': 'Next Card',
        'cards_to_go': '{count} to go',
        'cards_to_go_counter': '{current} / {total}',
        'show_answer': 'Show Answer',
        'feedback_again': 'Again',
        'feedback_good': 'Good',
        'no_flashcards_found': 'No flashcards found',
        'all_cards_learned_title': 'All Cards Learned!',
        'all_cards_learned_desc': 'Good job! You have studied all the cards for this session. Come back later for review.',
        'choose_other_method_button': 'Choose Other Mode',
        'reset_and_start_over_button': 'Reset & Restart',
        'session_complete': 'Session Complete!',
        'your_score': 'Your score: {correct} / {total}',
        'your_grade': 'Your Grade',
        'well_done_message': 'Well done! Keep practicing.',
        'focus_session': 'Focus',
        'break_session': 'Break',
        'Focusing on:': 'Focusing on:',
        'no_specific_task_option': 'No task selected',
        'set_added_success': 'Set created successfully.',
        'confirm_delete_set': 'Are you sure you want to delete the set "{name}" and all its cards?',
        'set_deleted_success': 'Set deleted successfully.',
        'error_empty_set_name': 'Set name cannot be empty.',
        'reset_srs_confirm': 'Are you sure you want to reset the learning progress (SRS) for this set?',
        'error_flashcard_set_min_cards': 'This mode requires at least 2 cards in the set.',
        'error_vocab_set_min_cards': 'This mode requires at least 1 card in the set.',
        'loading_cards': 'Loading cards...',
        'error_failed_to_load_cards': 'Could not load flashcards.',
        'error_failed_to_load_sets': 'Could not load sets.',
        'all_subjects_option': 'All Subjects',
        'add_note_button': 'New Note',
        'edit_note': 'Edit Note',
        'add_note_title_placeholder': 'Title',
        'add_note_content_placeholder': 'Start typing here...',
        'note_updated_success': 'Note updated successfully.',
        'note_added_success': 'Note added successfully.',
        'error_empty_note_title': 'Title cannot be empty.',
        'confirm_delete_note': 'Are you sure you want to delete this note?',
        'note_deleted_success': 'Note deleted successfully.',
        'set_reminder_title': 'Set reminder for: {task}',
        'reminder_date': 'Date',
        'reminder_time': 'Time',
        'save_reminder_button': 'Save Reminder',
        'remove_reminder_button': 'Remove Reminder',
        'task_reminder_title': 'Task Reminder',
        'error_failed_to_load_tasks': 'Could not load tasks.',
        'add_task_placeholder': 'Add a new task...',
        'add_task_button': 'Add',
        'no_tasks_found': 'No tasks found. Add one to get started!',
        'task_added_success': 'Task added successfully.',
        'task_updated_success': 'Task status updated.',
        'confirm_delete_task': 'Are you sure you want to delete this task?',
        'task_deleted_success': 'Task deleted successfully.',
        'notifications_denied_error': 'Notifications are blocked. Enable them in your browser settings.',
        'notifications_denied_prompt': 'You have not granted permission for notifications. The reminder will not be shown.',
        'error_empty_task': 'Task cannot be empty.',
        'grade_calculator_title': 'Grade Calculator',
        'grade_name_placeholder': 'Test name (optional)',
        'grade': 'Grade',
        'weight': 'Weight (%)',
        'add_grade': 'Add Grade',
        'current_average': 'Your current average:',
        'goal_calculator_title': 'Goal Calculator',
        'desired_average': 'Desired Average',
        'future_exam_weight': 'Weight of future exam (%)',
        'calculate_needed_grade': 'Calculate Needed Grade',
        'goal_easy_message': 'You are already above your goal. Great job!',
        'goal_impossible_message': 'It is mathematically impossible to reach your goal. The highest possible is...',
        'grade_needed_message': 'You need to get a **{grade}** to have an average of **{desired_average}**.',
        'admin_dashboard': 'Admin Dashboard',
        'users': 'Users',
        'broadcasts': 'Broadcasts',
        'admin_feedback_dashboard': 'Feedback',
        'loading_data': 'Loading data...',
        'last_login': 'Last Login',
        'status': 'Status',
        'actions': 'Actions',
        'active': 'Active',
        'disabled': 'Disabled',
        'enable_user': 'Enable user',
        'disable_user': 'Disable user',
        'refresh_data': 'Refresh',
        'confirm_disable_user': 'Are you sure you want to disable user {name}?',
        'confirm_enable_user': 'Are you sure you want to enable user {name}?',
        'user_status_updated': 'User status updated successfully.',
        'error_user_status_update': 'Could not update user status.',
        'send_broadcast': 'Send Broadcast',
        'broadcast_title_placeholder': 'Title',
        'broadcast_message_placeholder': 'Type your message here...',
        'sending': 'Sending...',
        'send_message_button': 'Send Message',
        'error_broadcast_empty': 'Title and message cannot be empty.',
        'broadcast_success': 'Broadcast sent successfully.',
        'error_broadcast_failed': 'Could not send broadcast.',
        'past_broadcasts': 'Past Broadcasts',
        'delete_all_broadcasts': 'Delete All',
        'no_past_broadcasts': 'No past broadcasts.',
        'confirm_delete_all_broadcasts_and_notifications': 'Are you sure you want to delete ALL broadcasts and their corresponding notifications for all users? This cannot be undone.',
        'all_broadcasts_deleted': 'All broadcasts and notifications have been deleted.',
        'error_deletion_failed': 'Deletion failed.',
        'from': 'From',
        'submitted_on': 'Submitted on',
        'status_new': 'New',
        'status_replied': 'Replied',
        'reply_to_feedback': 'Reply to Feedback',
        'your_reply_placeholder': 'Type your reply...',
        'send_reply_button': 'Send Reply',
        'reply_sent_success': 'Reply sent successfully.',
        'error_reply_failed': 'Could not send reply.',
        'admin_select_feedback': 'Select a feedback message to view details and reply.',
        'admin_streak_leaderboard': 'Streak Leaderboard',
        'no_streak_users': 'No users with an active streak.',
        'admin_appearance_settings': 'Appearance Settings (Admin)',
        'admin_security_settings': 'Security Settings',
        'admin_pin_toggle_label': 'Enable PIN protection on startup',
        'admin_pin_verify_title': 'PIN Verification',
        'admin_pin_verify_desc': 'To change this setting, you must answer the security question.',
        'admin_pin_answer_placeholder': 'Your answer',
        'admin_pin_error_incorrect': 'Incorrect answer.',
        'no_avatar_option': 'No avatar',
        'avatar_selection_title': 'Choose your avatar',
        'save_avatar_button': 'Save',
        'back': 'Back',
        'mark_all_as_read': 'Mark all as read',
        'confirm_clear_all_notifications': 'Are you sure you want to delete all notifications?',
        'content_per_subject': 'Content per Subject',
        'notifications_cleared': 'Notifications cleared.',
        'no_notifications': 'You have no new notifications.',
        'no_notifications_disabled_title': 'Notifications are disabled',
        'no_notifications_disabled_text': 'You will not receive any alerts. You can change this in the settings.',
        'intro_step1_title': 'Welcome to StudyBox!',
        'intro_step1_text': 'Your personal assistant for school. Organize your files, calendar, and notes in one place.',
        'intro_step2_title': 'Manage your Calendar',
        'intro_step2_text': 'Add tests, homework, and deadlines. Never miss an important date again!',
        'intro_step3_title': 'Powerful Tools',
        'intro_step3_text': 'Create flashcards with smart repetition (SRS), write notes, use the Pomodoro timer, and even let the AI create a whole study plan for you!',
        'intro_step4_title': 'Make it Your Style',
        'intro_step4_text': 'Choose your own color theme and font. Make StudyBox your personal study environment.',
        'intro_step5_title': 'Ready to Start!',
        'intro_step5_text': 'You are all set. Let\'s start organizing your success!',
        'intro_finish_button': 'Let\'s Go!',
        'ai_chat_welcome': 'Hi {userName}! I am {botName}, your personal study assistant. How can I help you today?',
        'ai_chat_placeholder': 'Ask {botName} a question...',
        'study_planner': 'Study Planner',
        'study_planner_title': 'Study Planner',
        'plan_for_date': 'Test on {date}',
        'registration_goal_title': 'What is your main goal?',
        'registration_almost_there': 'Almost there!',
        'goal_higher_grades': 'Get higher grades',
        'goal_be_organized': 'Stay organized',
        'goal_better_planning': 'Plan better',
        'goal_less_stress': 'Less stress',
        'hours': 'hours',
        'in_progress_badge': ' in progress ',
        'activity_type_file': 'File',
        'activity_type_note': 'Note',
        'activity_type_plan': 'Plan',
        'activity_type_set': 'Flashcards',
        'tasks_completed': 'Tasks completed (this week)',
        'study_time_minutes': 'Study minutes (this week)',
        'flashcards_created': 'New sets (this week)',
        'todays_events': 'Events today',
        'flashcard_ai_modal_title': 'Generate with AI',
        'flashcard_ai_modal_desc': 'Paste your notes or any text below, and the AI will automatically create flashcards from it.',
        'flashcard_ai_topic_placeholder': 'Topic (e.g., The French Revolution)',
        'flashcard_ai_placeholder': 'Paste your text here...',
        'generate_button': 'Generate',
        'flashcards_creating_message': 'Creating flashcards...',
        'ai_checking_answer': 'Checking...',
        'submit_answer': 'Check Answer',
        'ai_feedback_correct': 'Correct!',
        'ai_feedback_incorrect': 'Sorry, the correct answer was: {correct_answer}',
        'session_summary_title': 'Session Summary',
        'stars_earned_title': 'Stars Earned!',
        'correct_answers': 'Correct',
        'incorrect_answers': 'Incorrect',
        'time_spent': 'Time',
        'new_set_name_prompt': 'Enter a name for the new set with incorrect answers:',
        'practice_incorrect': 'Practice Incorrect Answers',
        'new_set_created_success': 'New set "{name}" created successfully!',
        'no_incorrect_answers': 'No incorrect answers to practice!',
        'create_set_from_incorrect': 'Create Set from Incorrect',
        'correct_answer': 'Correct answer',
        'your_answer': 'Your answer',
        'exit_session_confirm': 'Are you sure you want to end the session? Your progress will be lost.',
        'error_select_min_two_sets': 'Select at least two sets to combine.',
        'combined_set_name': 'Combined Set ({count})',
        'shared_by': 'Shared by {name}',
        'ai_no_events_found': 'The AI could not find any clear events in the text.',
        'ai_parsing_error': 'An error occurred while analyzing the text. Please try again.',
        'analyzing': 'Analyzing...',
        'analyze_button': 'Analyze Text',
        'review_schedule': 'Review Schedule',
        'import_for_weeks': 'Import for',
        'weeks': 'weeks',
        'edit_text_button': 'Edit Text',
        'importing': 'Importing...',
        'import_button': 'Import',
        'import_success': '{count} events imported successfully!',
        'import_error': 'Import failed.',
        'download_agenda': 'Download Calendar',
        'download_weeks_label': 'Download for the next',
        'download_format_label': 'Choose a format',
        'downloading_and_started': 'Downloading...',
        'download_button': 'Download',
        'sync_calendar_title': 'Sync your Calendar',
        'sync_calendar_desc': 'Sync external calendars (like school schedules) via an iCal link.',
        'get_ical_link': 'Find your iCal link',
        'how_to_get_link': 'Click your provider for a guide:',
        'paste_ical_link': 'Paste your iCal link',
        'calendar_name': 'Name of calendar (e.g., School Schedule)',
        'select_provider': 'Select provider',
        'calendar_url': 'Paste the iCal link here (webcal:// or https://)',
        'save_calendar': 'Save Calendar',
        'synced_calendars': 'Synced Calendars',
        'no_synced_calendars': 'No calendars synced yet.',
        'sync_calendar_tutorial_google': 'https://support.google.com/calendar/answer/37648?hl=en',
        'sync_calendar_tutorial_apple': 'https://support.apple.com/guide/calendar/subscribe-to-calendars-icl1022/mac',
        'sync_calendar_tutorial_teams': 'https://support.microsoft.com/en-us/office/see-a-channel-calendar-in-microsoft-teams-5203f61a-03e5-45a8-b636-121087278278',
        'sync_calendar_tutorial_canvas': 'https://community.canvaslms.com/t5/Student-Guide/How-do-I-subscribe-to-the-Calendar-feed-using-Google-Calendar/ta-p/413',
        'sync_calendar_tutorial_magister': 'https://www.google.com/search?q=magister+calendar+ical+link',
        'settings_sync_calendar': 'Sync',
        'weekly_overview': 'Week Overview',
        'planner_task': 'Study Task',
        'planner_tip': 'Tip',
        'error_all_fields_required': 'Please fill in all required fields.',
        'planner_create_your_schedule': 'Create your study plan',
        'planner_select_subject': 'Choose a subject',
        'planner_topic_placeholder': 'Topic(s) of the test',
        'planner_amount_placeholder': 'Amount of material (e.g., Ch. 1-3)',
        'planner_generating': 'Generating...',
        'planner_generate_button': 'Generate Plan',
        'planner_error_text': 'The AI could not create a schedule. Try making the input clearer or check your existing calendar for conflicts.',
        'planner_error_title': 'Oops, something went wrong!',
        'planner_result_title': 'Your Study Plan for {subject}',
        'planner_start_over': 'Start Over',
        'create_new_plan': 'Create New Plan',
        'plan_title_placeholder': 'Name of your plan (e.g., History Midterms)',
        'subject': 'Subject',
        'add_subject_button': 'Add Subject',
        'plan_test_date': 'Date of the test',
        'creating_plan': 'Creating plan...',
        'plan_created_success': 'Study plan successfully created and added to your calendar!',
        'delete_plan_confirm': 'Are you sure you want to delete this plan?',
        'plan_deleted_success': 'Plan successfully deleted.',
        'select_all_button': 'Select All',
        'delete_selected_button': 'Delete',
        'confirm_delete_plans': 'Are you sure you want to delete {count} plans?',
        'error_share_invalid_email': 'Please enter a valid email address.',
        'error_cannot_share_with_self': 'You cannot share with yourself.',
        'error_user_not_found': 'No user found with email: {email}.',
        'share_plan_success': 'Plan successfully shared with {email}!',
        'error_share_plan_failed': 'Failed to share plan.',
        'share_plan_title': 'Share "{title}"',
        'share_with_email': 'Share with email address',
        'share_set_title': 'Share set "{name}"',
        'share_success': 'Set successfully shared with {email}!',
        'error_share_failed': 'Sharing failed.',
        'verify_user_button': 'Manually verify user',
        'confirm_verify_user': 'Are you sure you want to manually verify {name}?',
        'user_verified_success': 'User successfully verified.',
        'error_user_verify_failed': 'Failed to verify user.',
        'feedback_title': 'Feedback & Support',
        'feedback_subtitle': 'Have a question, suggestion, or found a bug? Let us know!',
        'feedback_subject_placeholder': 'Subject',
        'feedback_message_placeholder': 'Your message...',
        'feedback_sent_success': 'Feedback sent successfully. Thank you!',
        'error_feedback_failed': 'Failed to send feedback.',
        'send_feedback_button': 'Send Feedback',
        'your_feedback_history': 'Your Feedback History',
        'no_feedback_history': 'You have not sent any feedback yet.',
        'new_chat': 'New Chat',
        'chat_history_title': 'Chat History',
        'verify_email_title': 'Verify your email address',
        'verify_email_instructions': 'We sent a verification link to {email}. Click the link in the email to activate your account.',
        'verify_email_spam_check': 'Didn\'t receive an email? Check your spam folder.',
        'verify_email_continue_button': 'I have verified my email',
        'email_sent': 'Email sent!',
        'verify_email_resend_button': 'Resend',
        'no_plans_yet': 'No study plans yet.',
        'no_plans_cta': 'Let the AI create a plan for you!',
        'error_ai_check_failed': 'AI check failed, please check manually.',
        'items': 'items',
        'no_data_for_chart': 'No data for this chart.',
        'event_type_distribution': 'Event Type Distribution',
        'progress': 'Progress',
        'time_spent_per_subject': 'Time Spent per Subject',
        'total_items': 'Total Items',
        'total_study_time': 'Total Study Time'
    }
};
